### ISSUE TITLE
How does VLM interact with physics simulation engines?

### ISSUE THREAD

**Issue by KeliangLiu2023** [Genesis-Embodied-AI/Genesis#155]
Hello, I would like to ask what role VLM played in this project? How does VLM interact with physics simulation engines? I don't think I saw that part of the supporting paper.
您好，我想问一下VLM在这个项目中起到了什么作用？VLM是如何与物理仿真引擎之间的联动的？我好像貌似没看见这部分的支持论文。

**Comment by ziyanx02** [comment]
Please follow #6 for updates on the generative framework. VLM will be included in the following works.
I will close this issue as it is not related to the simulator.

**Comment by BurhanUlTayyab** [comment]
Understand that you guys will release it later. But we are more interested in understanding how VLM interacts with the simulator.

**Comment by zhouxian** [comment]
> Understand that you guys will release it later. But we are more interested in understanding how VLM interacts with the simulator.

Yeah sure -- the idea is actually quite simple: we made the APIs simple enough so that it's understandable by LLM, then we just ask LLM to write code. The capability for writing simulation code is way below the limit of today's LLM's coding ability.

There are also of course other modules involved, but the basic idea is instead of learning everything end-to-end with a gigantic neural network, we generate stuff by using physics engine as a tool and simply write code
