### ISSUE TITLE
Can I move 2 robot simultaneously?

### ISSUE THREAD

**Issue by milong26** [Genesis-Embodied-AI/Genesis#382]
I want to let frank1 and frank2 move togerther(no collision problem)
```
qpos2 = franka2.inverse_kinematics(
    link = end_effector2,
    pos  = np.array([0.1, 0.0, 0.3]),
    quat = np.array([0, 1, 0, 0]),
)
franka2.control_dofs_position(qpos2[:-2], motors_dof2)
qpos1 = franka1.inverse_kinematics(
    link = end_effector1,
    pos  = np.array([-0.1, 0.0, 0.3]),
    quat = np.array([0, 1, 0, 0]),
)
franka1.control_dofs_position(qpos1[:-2], motors_dof1)
for i in range(200):
    scene.step()
```
But with the code above frank2 works a bit earlier than frank1. [Parallel Simulation](https://genesis-world.readthedocs.io/en/latest/user_guide/getting_started/parallel_simulation.html) gives a parallel example but my 2 robots are different in quat and pos. 

THanks!

**Comment by zhouxian** [comment]
Firstly, parallel simiulation would work because you can set different base pos quat for different envs

Secondly, if you want to control both, there are two ways:
- instead of using `entity.control_dofs_position`, you could use the global level solver controller - `scene.rigid_solver.control_dofs_position`, note that the only difference is the `motor_dofs` you give are the global one
- you can also implement your own PD controller, which is a common practice in locomotion skill training
