### ISSUE TITLE
Any timepline of open source

### ISSUE THREAD

**Issue by YunxiTang** [Genesis-Embodied-AI/Genesis#4]
Hi,
is there any timeline for open sourcing this project?

**Comment by Milotrince** [comment]
I heard early December but we never know...

**Comment by zhouxian** [comment]
Hi, thank you for your interest in our project! We planned to release it last week (before my phd defense) but in order to polish up some demo associated with it, we decided to postpone it a bit and I had to spend some time on my graduation-related matters. Now everything is ready for release and we are finalizing some humanoid demo, but we accidentally broke a humanoid hardware and we are migrating to a more complex platform, which drags the progress a little bit further. We promise to release it in early december :)

**Comment by sxyu** [comment]
Hi, is there any update on the timeline? Thanks
